"""create prepared artifacts

Revision ID: 1208bd1c9937
Revises: 80ae2d1efb45
Create Date: 2026-08-13 04:38:17.984333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1208bd1c9937'
down_revision: Union[str, Sequence[str], None] = '80ae2d1efb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prepared_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('preparation_job_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version', sa.String(length=20), nullable=False),
    sa.Column('artifact_id', sa.String(length=100), nullable=False),
    sa.Column('train_object_key', sa.Text(), nullable=False),
    sa.Column('validation_object_key', sa.Text(), nullable=False),
    sa.Column('test_object_key', sa.Text(), nullable=False),
    sa.Column('manifest_object_key', sa.Text(), nullable=False),
    sa.Column('train_record_count', sa.Integer(), nullable=False),
    sa.Column('validation_record_count', sa.Integer(), nullable=False),
    sa.Column('test_record_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['preparation_job_id'], ['preparation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_index(op.f('ix_prepared_artifacts_dataset_id'), 'prepared_artifacts', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_prepared_artifacts_preparation_job_id'), 'prepared_artifacts', ['preparation_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prepared_artifacts_preparation_job_id'), table_name='prepared_artifacts')
    op.drop_index(op.f('ix_prepared_artifacts_dataset_id'), table_name='prepared_artifacts')
    op.drop_table('prepared_artifacts')
    # ### end Alembic commands ###
