"""create preparation quality reports

Revision ID: 4355f89664f4
Revises: 1208bd1c9937
Create Date: 2026-08-13 04:54:01.259296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4355f89664f4'
down_revision: Union[str, Sequence[str], None] = '1208bd1c9937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preparation_quality_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('preparation_job_id', sa.UUID(), nullable=False),
    sa.Column('prepared_artifact_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failed_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preparation_job_id'], ['preparation_jobs.id'], ),
    sa.ForeignKeyConstraint(['prepared_artifact_id'], ['prepared_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_quality_reports_preparation_job_id'), 'preparation_quality_reports', ['preparation_job_id'], unique=False)
    op.create_index(op.f('ix_preparation_quality_reports_prepared_artifact_id'), 'preparation_quality_reports', ['prepared_artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preparation_quality_reports_prepared_artifact_id'), table_name='preparation_quality_reports')
    op.drop_index(op.f('ix_preparation_quality_reports_preparation_job_id'), table_name='preparation_quality_reports')
    op.drop_table('preparation_quality_reports')
    # ### end Alembic commands ###
